version: '2.1'

services:
  postgres:
    image: postgres:11
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=${DBNAME}
     - POSTGRES_USER=${DBUSER}
     - POSTGRES_PASSWORD=${DBPASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - 9000:9000
    env_file:
      - $PWD/.env
    depends_on: 
      postgres:
        condition: service_healthy
